export {default as MyProfile} from './MyProfile/MyProfile.js'
export {default as Header} from './Header/Header.js'
export {default as Sidebar} from './Sidebar/Sidebar.js'
export {default as Main} from './Main/Main'
export {default as Login} from './Login/Login'
export {default as Signup} from './Signup/Signup'
export {default as SelectVideo} from './UploadVideo/SelectVideo'
